# Generated by Django 5.2.13 on 2026-07-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0119_alter_stockitemtestresult_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="size",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional size information for this stock item",
                max_length=100,
                verbose_name="Size",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="sterile",
            field=models.CharField(
                blank=True,
                choices=[("S", "Sterile"), ("NS", "Non-sterile")],
                default="",
                help_text="Sterility status for this stock item",
                max_length=2,
                verbose_name="Sterile",
            ),
        ),
    ]
