# Generated by Django 5.2.13 on 2026-07-20 17:41

import InvenTree.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import vhc.models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stock", "0119_alter_stockitemtestresult_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoxSequence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(unique=True)),
                ("next_value", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "verbose_name": "VHC Box Number Sequence",
            },
            bases=(
                InvenTree.models.ContentTypeMixin,
                InvenTree.models.PluginValidationMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Pallet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "VHC Pallet",
                "verbose_name_plural": "VHC Pallets",
                "ordering": ["shipment", "number"],
            },
            bases=(
                InvenTree.models.ContentTypeMixin,
                InvenTree.models.PluginValidationMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Reference"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(default=vhc.models.current_year)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CONTAINER", "Container"),
                            ("TRUNK", "Trunk"),
                            ("OTHER", "Other"),
                        ],
                        default="CONTAINER",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("PACKING", "Packing"),
                            ("IN_TRANSIT", "In transit"),
                            ("ARRIVED", "Arrived"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("arrival_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "VHC Shipment",
                "verbose_name_plural": "VHC Shipments",
                "ordering": ["-year", "reference"],
            },
            bases=(
                InvenTree.models.ContentTypeMixin,
                InvenTree.models.PluginValidationMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z0-9_]+$")
                        ],
                        verbose_name="Code",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#228BE6",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a color in #RRGGBB format",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="Sticker color",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Display order"
                    ),
                ),
            ],
            options={
                "verbose_name": "VHC Team",
                "verbose_name_plural": "VHC Teams",
                "ordering": ["display_order", "name"],
            },
            bases=(
                InvenTree.models.ContentTypeMixin,
                InvenTree.models.PluginValidationMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "box_number",
                    models.CharField(
                        max_length=6,
                        blank=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Box number must contain exactly six digits",
                                regex="^\\d{6}$",
                            )
                        ],
                        verbose_name="Box number",
                    ),
                ),
                ("contents", models.TextField(max_length=500, verbose_name="Contents")),
                (
                    "other_team_description",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Other team description",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, max_length=500, verbose_name="Note"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PACKED", "Packed"),
                            ("PALLETIZED", "Palletized"),
                            ("IN_TRANSIT", "In transit"),
                            ("HONDURAS_WAREHOUSE", "Honduras warehouse"),
                            ("DISTRIBUTED", "Distributed"),
                            ("RETURNED", "Returned"),
                            ("LOST", "Lost"),
                            ("CLOSED", "Closed / empty"),
                        ],
                        default="PACKED",
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("DONATION_PURCHASE", "Donation / purchase"),
                            ("CONTAINER_ARRIVAL", "Container arrival"),
                            ("RETURNED_INVENTORY", "Returned inventory"),
                            ("HONDURAS_PURCHASE", "Local Honduras purchase"),
                            ("ADJUSTMENT", "Stock adjustment"),
                        ],
                        default="DONATION_PURCHASE",
                        max_length=30,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vhc_boxes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vhc_boxes",
                        to="stock.stocklocation",
                        verbose_name="Current location",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vhc_destination_boxes",
                        to="stock.stocklocation",
                        verbose_name="Destination",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vhc_boxes_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boxes",
                        to="vhc.pallet",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boxes",
                        to="vhc.shipment",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boxes",
                        to="vhc.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "verbose_name": "VHC Box",
                "verbose_name_plural": "VHC Boxes",
                "ordering": ["-created", "-pk"],
            },
            bases=(
                InvenTree.models.InvenTreeAttachmentMixin,
                InvenTree.models.ContentTypeMixin,
                InvenTree.models.PluginValidationMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="BoxEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("EDITED", "Edited"),
                            ("MOVED", "Moved"),
                            ("PALLETIZED", "Palletized"),
                            ("DISTRIBUTED", "Distributed"),
                            ("RETURNED", "Returned"),
                            ("LOST", "Marked lost"),
                            ("CLOSED", "Closed / empty"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="vhc.box",
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "VHC Box Event",
                "verbose_name_plural": "VHC Box Events",
                "ordering": ["-timestamp", "-pk"],
            },
            bases=(
                InvenTree.models.ContentTypeMixin,
                InvenTree.models.PluginValidationMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="pallet",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pallets",
                to="vhc.shipment",
            ),
        ),
        migrations.AddConstraint(
            model_name="pallet",
            constraint=models.UniqueConstraint(
                fields=("shipment", "number"), name="unique_vhc_pallet_per_shipment"
            ),
        ),
    ]
