# Generated by Django 5.2.13 on 2026-07-20 19:46

import decimal

import InvenTree.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0147_remove_part_default_supplier"),
        ("stock", "0119_alter_stockitemtestresult_date"),
        ("vhc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="contents",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Generated summary of the structured box items",
                max_length=500,
                verbose_name="Contents",
            ),
        ),
        migrations.CreateModel(
            name="BoxItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.00001"))],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="vhc.box",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vhc_box_items",
                        to="part.part",
                    ),
                ),
                (
                    "stock_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vhc_box_item",
                        to="stock.stockitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "VHC Box Item",
                "verbose_name_plural": "VHC Box Items",
                "ordering": ["part__name", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("box", "part"), name="unique_vhc_part_per_box"
                    )
                ],
            },
            bases=(
                InvenTree.models.ContentTypeMixin,
                InvenTree.models.PluginValidationMixin,
                models.Model,
            ),
        ),
    ]
