# Generated by Django 5.2.13 on 2026-07-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vhc", "0002_alter_box_contents_boxitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxitem",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boxitem",
            name="size",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="boxitem",
            name="sterile",
            field=models.CharField(
                blank=True,
                choices=[("S", "Sterile"), ("NS", "Non-sterile")],
                default="",
                max_length=2,
            ),
        ),
    ]
